### ISSUE TITLE
Exception when searching for string inside method call

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/sgrep#104]
**Describe the bug**
Searching for this code:

```py
logging.info(
        f"Current bento version is {current_version}, latest is {latest_version}"
    )
```

I'd like to identify that `bento` should be uppercase.

```yaml
rules:
    - id: bento
      patterns:
        - pattern: $X("=~/.*bento.*/")
      message: Bento should be capitalized.
      languages: [python]
      severity: ERROR
```

The error is:

```
running 1 rules from 1 yaml files (0 yaml files were invalid)
Fatal error: exception (Failure "get_pos: Ab or FakeTok")
Traceback (most recent call last):
  File "/bin/sgrep-lint", line 851, in <module>
    main(args)
  File "/bin/sgrep-lint", line 701, in main
    output_json = invoke_sgrep(all_patterns, targets)
  File "/bin/sgrep-lint", line 325, in invoke_sgrep
    output = subprocess.check_output(cmd, shell=False)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sgrep', '-lang', 'python', '-rules_file', '/tmp/tmpu09opzct', '/home/repo']' returned non-zero exit status 2.
```

**To Reproduce**
1. `git clone git@github.com:returntocorp/bento.git`
2. Run the above rule

**Comment by aryx** [comment]
Can't reproduce either.
