### ISSUE TITLE
Exception finding patterns inside nested function calls

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/sgrep#106]
**Describe the bug**
To identify the code:

```py
click.echo(click.style(f"Detected project with {projects}\n", fg="blue", err=True))
```

```yaml
rules:
    - id: use-click-secho
      pattern: click.echo(click.style($X, ...))
      message: Use `click.secho($X)` instead. It combines click.echo() and click.style().
      languages: [python]
      severity: ERROR
```

I get the following exception:

```
Fatal error: exception (Failure "get_pos: Ab or FakeTok")
Traceback (most recent call last):
  File "/bin/sgrep-lint", line 851, in <module>
    main(args)
  File "/bin/sgrep-lint", line 701, in main
    output_json = invoke_sgrep(all_patterns, targets)
  File "/bin/sgrep-lint", line 325, in invoke_sgrep
    output = subprocess.check_output(cmd, shell=False)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sgrep', '-lang', 'python', '-rules_file', '/tmp/tmpckk6dtz6', '/home/repo']' returned non-zero exit status 2.
```

**Comment by aryx** [comment]
You probably used an older version of sgrep, the one from the master branch instead of develop.
I can't reproduce with latest:
 /home/pad/github/sgrep/_build/default/bin/main_sgrep.exe -e click.echo(click.style($X, ...)) ./tests/python/misc_faketok.py
/home/pad/github/sgrep/tests/python/misc_faketok.py:3
     click.echo(click.style(f"Detected project with {projects}\n", fg="blue", err=True))

No exceptions.

**Comment by aryx** [comment]
Note that the pattern you wrote will not detect code like
            click.echo(f"    $ {click.style(cmd, bold=True)}\n", err=True)

**Comment by dlukeomalley** [comment]
I pulled latest develop and still get this error. You can reproduce this error by running this rule on bento-core.

**Comment by ievans** [comment]
To be specific:

on bento-core,
```
> git checkout lomalley/sgrep-test
> docker run --rm -v (pwd):/home/repo returntocorp/sgrep:develop
running 1 rules from 1 yaml files (0 yaml files were invalid)
Fatal error: exception (Failure "get_pos: Ab or FakeTok")
Traceback (most recent call last):
  File "/bin/sgrep-lint", line 1004, in <module>
    main(args)
  File "/bin/sgrep-lint", line 845, in main
    output_json = invoke_sgrep(all_patterns, targets)
  File "/bin/sgrep-lint", line 346, in invoke_sgrep
    output = subprocess.check_output(cmd, shell=False)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sgrep', '-lang', 'python', '-rules_file', '/tmp/tmp5hu9pim5', '/home/repo']' returned non-zero exit status
```
