### ISSUE TITLE
Return $X pattern is failing in tests

### ISSUE THREAD

**Issue by ulziibay** [returntocorp/sgrep#73]
**Describe the bug**
When the return $X is used in sgrep pattern, the rule engine is failing with the following:
```
Fatal error: exception (Failure "get_pos: Ab or FakeTok")
```

**To Reproduce**
1. Check out 2248c2570a0b6228b537d41afa11766d590a7fc8
2. `make build`
3. Create the following rule file
```
rules:
    - id: return-in-init
      patterns:
        - pattern-inside: |
            class A(...):
              ...
        - pattern-inside: |
            def __init__(...):
              ...
        - pattern: return $X
      message: "`return` should never appear inside a class __init__ function"
      languages: [python]
      severity: ERROR
```
4. Pass in to sgrep binary:
```
./sgrep.py -f ~/Workspace/sgrep-rules/python/smells/return-in-init.yaml ~/Workspace/pyyaml
```
5. See
```
running 1 rules from 1 yaml files (0 yaml files were invalid)
Fatal error: exception (Failure "get_pos: Ab or FakeTok")
Traceback (most recent call last):
  File "./sgrep.py", line 779, in <module>
    main(args)
  File "./sgrep.py", line 641, in main
    output_json = invoke_sgrep(all_patterns, targets)
  File "./sgrep.py", line 291, in invoke_sgrep
    output = subprocess.check_output(cmd, shell=False)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sgrep', '-rules_file', '/var/folders/7c/2qqryd9n42b9v778dlpdhqgw0000gn/T/tmp1gwgxhqz', '/Users/ulziibayarotgonbaatar/Workspace/pyyaml']' returned non-zero exit status 2.
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ulziibay** [comment]
Potential duplication or reincarnation of https://github.com/returntocorp/sgrep/issues/52
